DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
  employee_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER NOT NULL,
  manager_id INTEGER NOT NULL
);

CREATE TABLE role (
 id_role INTEGER AUTO_INCREMENT PRIMARY KEY,
 role_name VARCHAR(30) NOT NULL,
 salary DECIMAL NOT NULL,
 department_id INTEGER NOT NULL
);

CREATE TABLE department (
 id INTEGER AUTO_INCREMENT PRIMARY KEY,
 department_name VARCHAR(30) NOT NULL
);